version: '3.7'

services:
  redis-test:
    image: redis
    container_name: redis-test
    ports:
      - "6381:6381"
    expose:
      - 6381
    command: --port 6381
    restart:
      always

  server-test:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    environment:
      - NODE_ENV=test
      - SERVER_PORT=4002
      - REDIS_HOST=redis-test
      - REDIS_PORT=6381
    links:
      - redis-test
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: server-test
    depends_on:
      - redis-test
    expose:
      - '4002'
    ports:
      - '4002:4002'
    command: npm run test
