version: '3.7'

services:
  redis-dev:
    image: redis
    container_name: redis-cache
    ports:
      - "6379:6379"
    expose:
      - 6379
    command: --save 1 1 --loglevel warning
    restart:
      always

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis-dev
    links:
      - redis-dev
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: server-docker
    depends_on:
      - redis-dev
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev
