version: '3.7'

services:
  redis-dev:
    image: redis
    container_name: redis-dev
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    expose:
      - 6379
    command: --port 6379 --save 1 1 --loglevel warning
    restart:
      always

  server-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    environment:
      - NODE_ENV=development
      - SERVER_PORT=4000
      - REDIS_HOST=redis-dev
      - REDIS_PORT=6379
    links:
      - redis-dev
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: server-dev
    depends_on:
      - redis-dev
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev
volumes:
  redis_data:
